// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthToken struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type Footer struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Data      string `json:"data"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type FooterInput struct {
	ID   *string `json:"id,omitempty"`
	Name string  `json:"name"`
	Data string  `json:"data"`
}

type Header struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Data      string `json:"data"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type HeaderInput struct {
	ID   *string `json:"id,omitempty"`
	Name string  `json:"name"`
	Data string  `json:"data"`
}

type Mutation struct {
}

type Page struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	Data      string `json:"data"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type PageInput struct {
	ID   *string `json:"id,omitempty"`
	Name string  `json:"name"`
	Slug string  `json:"slug"`
	Data string  `json:"data"`
}

type Query struct {
}
