// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthToken struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type Mutation struct {
}

type Query struct {
}
